#!/usr/bin/env bash

sudo apt-get install \
  software-properties-common \
  python-software-properties \
  python-dev \
  python-pip \
  python3-dev \
  python3-pip \
  exuberant-ctags

sudo add-apt-repository ppa:neovim-ppa/unstable
sudo apt-get update
sudo apt-get install neovim

sudo update-alternatives --install /usr/bin/vi vi /usr/bin/nvim 60
sudo update-alternatives --config vi
sudo update-alternatives --install /usr/bin/vim vim /usr/bin/nvim 60
sudo update-alternatives --config vim
sudo update-alternatives --install /usr/bin/editor editor /usr/bin/nvim 60
sudo update-alternatives --config editor

curl vimfiles.luan.sh/install | bash
